var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0q~8mz9._.js")
R.c("server/chunks/ssr/0xhq_0a15pus._.js")
R.c("server/chunks/ssr/0xhq_next_dist_esm_build_templates_app-page_0u7usgf.js")
R.c("server/chunks/ssr/[root-of-the-server]__12sj6.j._.js")
R.c("server/chunks/ssr/[root-of-the-server]__01tmjoz._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0an9b73._.js")
R.c("server/chunks/ssr/0xhq_next_dist_client_components_0uk45rq._.js")
R.c("server/chunks/ssr/0xhq_next_dist_client_components_builtin_forbidden_0btu3ps.js")
R.c("server/chunks/ssr/0xhq_next_dist_client_components_builtin_unauthorized_0ukqkzb.js")
R.c("server/chunks/ssr/0xhq_next_dist_client_components_builtin_global-error_0xpq89-.js")
R.c("server/chunks/ssr/0m4n_GitHub_cv-website_cv-website__next-internal_server_app_page_actions_02xw0o..js")
R.m(6368)
module.exports=R.m(6368).exports
